### Find all the content
GET http://localhost:8080/api/content

### Get content by ID 
GET http://localhost:8080/api/content

### Create new content
POST http://localhost:8080/api/content
Content-Type: application/json

{
    "id": 2,
    "title": "My Second blog post",
    "desc": "My Second blog post",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2024-02-11T12:00:00",
    "dateUpdated": null,
    "url": ""
}


### Update existing content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
    "id": 1,
    "title": "MY FIRST POST!!!",
    "desc": "MY FIRST POST!!!",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2024-02-11T12:00:00",
    "dateUpdated": "2024-02-11T12:00:00",
    "url": "http://localhost:8080/my-first-blog-post"
}

### Update existing content with invalid id
PUT http://localhost:8080/api/content/99
Content-Type: application/json

{
    "id": 1,
    "title": "MY FIRST POST!!!",
    "desc": "MY FIRST POST!!!",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2024-02-11T12:00:00",
    "dateUpdated": "2024-02-11T12:00:00",
    "url": "http://localhost:8080/my-first-blog-post"
}

### delete by id
DELETE http://localhost:8080/api/content/2